version: "3.7"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.1
    container_name: filebeat
    user: root
    networks:
      - logger_server
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./test_log_filebeat:/var/log/:ro
    

  logstash:
      image: docker.elastic.co/logstash/logstash:7.12.1
      container_name: logstash
      environment:
           XPACK_MONITORING_ENABLED: "false"
      volumes:
        - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
        - ./config/pipelines:/usr/share/logstash/config/pipelines:ro
        - ./logs:/usr/share/logstash/input
        - ./output:/usr/share/logstash/output
      ports:
        - 5046:5046
      networks:
       - logger_server

networks:
  logger_server:
    driver: bridge

volumes:
  filebeat:
  logstash_data:


configs:
  fb_config:
    file: $PWD/filebeat/filebeat.yml   